#!/usr/bin/env python3
"""Compute the build version and generate installer/include/wkrl_version.h + installer/assets/param.json.

Version scheme:
    dev:          <base>-dev-<suffix>
    stable:       <base>
    pre-release:  <base>-pre-<suffix>

Usage:
    gen_version.py                 # (re)generate version header and app metadata
    gen_version.py --print         # print the full version string
"""

import datetime
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(REPO, "installer", "include", "wkrli_version.h")
WKRLI_H = os.path.join(REPO, "installer", "include", "wkrli.h")
PARAM_JSON = os.path.join(REPO, "installer", "assets", "param.json")
PARAM_TEMPLATE = os.path.join(REPO, "installer", "assets", "param.json.template")
VERSION_PLACEHOLDER = b"[[VERSION_PLACEHOLDER]]"


def read_base_version():
    """Read the base WKRLI_VERSION from installer/include/wkrli.h."""
    try:
        with open(WKRLI_H) as f:
            content = f.read()
        m = re.search(r'#define\s+WKRLI?_VERSION\s+"([^"]+)"', content)
        if m:
            return m.group(1)
    except OSError:
        pass
    return "0.1.0"


def git(*args):
    """Run a git command in the repo; returns stdout stripped or ''."""
    try:
        return subprocess.run(
            ["git", *args], cwd=REPO, capture_output=True, text=True, errors="replace"
        ).stdout.strip()
    except OSError:
        return ""


def get_version_info(build_type=None):
    """Compute version components."""
    if build_type is None:
        build_type = os.environ.get("BUILD_TYPE", "dev")
    if build_type not in ("dev", "stable", "pre-release"):
        build_type = "dev"

    base = read_base_version()
    custom = os.environ.get("CUSTOM_VERSION", "").strip()

    git_hash = git("rev-parse", "--short", "HEAD")
    dirty = git("status", "--porcelain")
    suffix = git_hash or "unknown"
    if dirty:
        suffix = datetime.datetime.now().strftime("%Y%m%d%H%M%S")

    if custom:
        full = f"{base}-{custom}"
    elif build_type == "stable":
        full = base
    else:
        segment = "pre" if build_type == "pre-release" else "dev"
        full = f"{base}-{segment}-{suffix}"

    return {
        "base": base,
        "build_type": build_type,
        "suffix": suffix,
        "full": os.environ.get("BUILD_VERSION") or full,
        "git_hash": git_hash or "unknown",
        "dirty": bool(dirty),
        "build_time": datetime.datetime.now(datetime.timezone.utc).strftime(
            "%Y-%m-%d %H:%M:%S UTC"
        ),
        "title": full if custom else base,
    }


def header_text(info):
    return (
        "#pragma once\n"
        "/* Auto-generated by tools/gen_version.py - do not edit. */\n"
        "\n"
        f'#define WKRLI_BASE_VERSION "{info["base"]}"\n'
        f'#define WKRLI_BUILD_TYPE "{info["build_type"]}"\n'
        f'#define WKRLI_BUILD_SUFFIX "{info["suffix"]}"\n'
        f'#define WKRLI_FULL_VERSION "{info["full"]}"\n'
        f'#define WKRLI_BUILD_TIME "{info["build_time"]}"\n'
        "\n"
        "/* Compatibility aliases */\n"
        "#define WKRL_BASE_VERSION WKRLI_BASE_VERSION\n"
        "#define WKRL_BUILD_TYPE WKRLI_BUILD_TYPE\n"
        "#define WKRL_BUILD_SUFFIX WKRLI_BUILD_SUFFIX\n"
        "#define WKRL_FULL_VERSION WKRLI_FULL_VERSION\n"
        "#define WKRL_BUILD_TIME WKRLI_BUILD_TIME\n"
        "\n"
    )


def write_if_changed(path, data):
    """Write bytes only when the content differs."""
    try:
        with open(path, "rb") as f:
            if f.read() == data:
                return
    except OSError:
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    if argv and argv[0] == "--print":
        print(get_version_info()["full"])
        return 0
    if argv and argv[0] == "--build-time":
        print(get_version_info()["build_time"])
        return 0
    if argv and argv[0] == "--title":
        info = get_version_info()
        print(f"PS5 WebKit Remote Loader v{info['full']} by PLK (built {info['build_time']})")
        return 0

    info = get_version_info()
    write_if_changed(HEADER, header_text(info).encode("utf-8"))

    if os.path.isfile(PARAM_TEMPLATE):
        with open(PARAM_TEMPLATE, "rb") as f:
            param = f.read()
        write_if_changed(
            PARAM_JSON, param.replace(VERSION_PLACEHOLDER, info["title"].encode("utf-8"))
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
